# Multiple languages
gems:             ['jekyll-multiple-languages']

languages:        ['es', 'en']

fill_default_content: true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Onodo
tagline:          Análisis de redes para todos
url:              http://onodo.org
baseurl:          
author:
  name:           Civio
  url:            http://civio.es
  email:          contacto@civio.es

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/civio/onodo.org
