# Multiple languages
# 20150306: This was breaking my build, don't know why. And the official way
# of including the plugin is through the _plugins/ folder, so we do that.
# See https://github.com/screeninteraction/jekyll-multiple-languages-plugin
#gems:             ['jekyll-multiple-languages']

languages:        ['es', 'en']

fill_default_content: true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Onodo
tagline:          Análisis de redes para todos
url:              https://onodo.org
baseurl:          
author:
  name:           Civio
  url:            https://civio.es
  email:          contacto@civio.es

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/civio/onodo.org
